"""s08 · 尾声 Epilogue (22 s) — owner: SCENE-BOOKENDS.

1. 0–9.8   Another night (dissolve in from s07's sunrise). The lighthouse lit, beam
           sweeping, Deng on the gallery with his new star-shaped heart, looking up.
           N05; the answering star right above the lighthouse flares exactly at `blink1`
           and `blink2` ("一闪，一闪") — sparkle burst + cross glints; his heart answers.
2. 9.2–15  `wave`: Deng waves up at the star (happy eyes). During N06 the camera cranes
           up and back: the lighthouse becomes tiny, the sky fills the frame.
3. 15–22   `end_title`: 一盏灯，一颗星 re-assembles from stardust streaming out of the
           answering star (same machinery as s01), with 完 · The End; `credits`; fade to
           black from `fade_out`.
"""
from __future__ import annotations

import math

import skia

from engine.core import (Camera, FONT_SERIF, H, W, clamp, col, draw_text, ease_in_out, ease_out,
                         ease_out_back, fill, font, lerp, smoothstep, soft_glow)
from lib import fx, robot, sea, sky

from scenes import _title
from scenes._s01_world import (draw_lighthouse_group, flare_env, hero_star, log_spline, spline, star_burst)

HZ = 720.0                 # reference horizon (sky-layer coords == screen when horizon is here)
D_SKY = 0.4
STAR = (880.0, 96.0)       # answering star in sky-layer coords
MW = dict(cx=760.0, cy=120.0, angle=-0.52, width=620.0)
TITLE_C = (960.0, 300.0)   # title centre, sky-layer coords

CREDITS = (
    ('画面、配音、音乐、音效 —— 全部由代码生成', 31, '#e6ebf7', 0.92),
    ('Every frame, voice, note and sound in this film was generated by code.', 25, '#c3cde2', 0.85),
    ('Python  ·  Skia  ·  Kokoro TTS  ·  FluidSynth  ·  Claude', 23, '#a9b8d8', 0.8),
)

_PT = None


def _flare(ts):
    """One 'blink' envelope (fast attack, ~0.9 s decay)."""
    fn = getattr(sky, 'hero_flare', None)
    if fn is not None:
        return fn(ts)
    return flare_env(ts, 0.0)


def _title_sys():
    global _PT
    if _PT is None:
        pt = _title.title_main('s08')
        pt.set_source_point(STAR[0] - TITLE_C[0], STAR[1] - TITLE_C[1], frac=0.4)
        _PT = pt
    return _PT


def _crane(f):
    """(start, end) of the crane up-and-back (during N06, after the wave has read)."""
    a = f.cue('N06_start') + 0.7
    return a, a + 5.2


def hz_at(f, t):
    a, b = _crane(f)
    return spline(t, [(0.0, 790.0), (a, 800.0), (b, 1010.0), (f.dur + 1, 1025.0)])


def _horizon(f):
    return hz_at(f, f.t)


def _lighthouse_frame(f, hz):
    t = f.t
    a, b = _crane(f)
    e = f.dur + 1
    s = log_spline(t, [(0.0, 4.7), (a, 4.2), (b, 0.3), (e, 0.27)])
    # focus point on the lighthouse (local) and where it sits on screen
    F = spline(t, [(0.0, (-35.0, -440.0)), (a, (-30.0, -445.0)), (b, (0.0, -300.0)), (e, (0.0, -300.0))])
    P = spline(t, [(0.0, (1010.0, 690.0)), (a, (1000.0, 672.0)), (b, (960.0, hz_at(f, b) + 18 - 300 * 0.3)),
                   (e, (960.0, hz_at(f, e) + 18 - 300 * 0.27))])
    return P[0] - F[0] * s, P[1] - F[1] * s, s


def _deng(f, blink_flare):
    t = f.t
    tw = f.cue('wave')

    def pose_fn(p, ctx):
        idl = robot.idle(f.T, seed=4)
        p.facing = -1.0
        p.turn = -0.3
        p.sit = 1.0
        p.sit_dangle = 1.0
        p.head_dy = idl['head_dy']
        p.lean = idl['lean'] - 0.04
        p.heart_star = 1.0
        p.heart_present = True
        p.heart = 1.0 + 0.5 * blink_flare
        p.scarf_wind = 0.55
        p.blink = robot.auto_blink(f.T, seed=5)
        p.mouth = f.mouth('deng')
        # gazing up at his star the whole time
        p.head_tilt = -0.24 + idl['head_tilt']
        p.look = (0.3, -0.95)
        p.eyes = 'wonder'
        p.eyes2 = 'happy'
        p.eyes_mix = clamp(blink_flare * 1.6)
        p.smile = 0.6 + 0.3 * blink_flare
        p.sit_kick = 0.3
        p.arm_r = (0.3 + 0.03 * math.sin(f.T * 0.8), 0.35)
        p.arm_l = (0.25, 0.3)
        p.hand_r_open = 0.4
        # wave: anticipation dip, arm swings up and out, waving, then settles back
        w = t - tw
        if w > -0.4:
            up = smoothstep(-0.05, 0.5, w) * (1 - smoothstep(3.9, 4.8, w))
            dip = 0.18 * math.exp(-((w + 0.12) / 0.13) ** 2)
            osc = math.sin(max(0.0, w - 0.45) * math.tau * 1.5) * smoothstep(0.4, 0.8, w) * (1 - smoothstep(3.4, 4.1, w))
            # the far arm (screen-left, towards the star) waves against the dark sky
            sh = lerp(0.25, 2.8, ease_out_back(clamp(up)) if up < 0.999 else 1.0) - dip + 0.1 * osc
            el = lerp(0.3, 0.35, up) + 0.38 * osc
            p.arm_l = (sh, el)
            p.hand_l_open = lerp(0.4, 1.0, up)
            p.eyes_mix = max(p.eyes_mix, smoothstep(0.1, 0.5, up))
            p.smile = lerp(p.smile, 1.0, up)
            p.head_dy += -3 * up
            p.lean -= 0.06 * up
            p.sit_kick = lerp(0.3, 0.8, up)
        return p
    return pose_fn


def render(f):
    c = f.canvas
    t = f.t
    T = f.T
    hz = _horizon(f)
    cam = Camera(x=W / 2, y=H / 2 - (hz - HZ), t=T)

    # star flares (exactly on the narrator's "一闪，一闪")
    b1, b2 = f.cue('blink1'), f.cue('blink2')
    fl = max(_flare(t - b1), _flare(t - b2))
    flare_age = (t - b2) if t >= b2 - 0.02 else (t - b1)
    twinkle_answer = 0.0
    tw = f.cue('wave')
    if t > tw + 0.6:  # a gentle answering twinkle after he waves
        twinkle_answer = max(0.4 * _flare(t - tw - 1.5), 0.3 * _flare(t - tw - 2.2))
        if t > tw + 1.45:
            flare_age = t - tw - (2.2 if t > tw + 2.2 else 1.5)
    flare = max(fl, twinkle_answer)

    # ---------------------------------------------------------------- sky
    with cam.apply(c, 1.0):
        sky.sky(c, horizon_y=HZ)
    hz_sky = HZ + (hz - HZ) * (1 - D_SKY)
    with cam.apply(c, D_SKY):
        sky.milky_way(c, T, center=(MW['cx'], MW['cy']), angle=MW['angle'], length=4200, width=MW['width'], alpha=0.5,
                      horizon_y=hz_sky)
        sky.stars(c, T, bright=1.0, horizon_y=hz_sky)
        # a lazy meteor while the camera cranes up
        mt = _crane(f)[0] + 1.6
        p = (t - mt) / 0.8
        if 0 <= p <= 1:
            fx.meteor(c, 380, -60, 120, 120, p, tail=220, size=0.3, t=T)
        # the answering star
        sx, sy = STAR
        hero_star(c, T, sx, sy, flare=flare, flare_age=None,
                  scale=1.25 + 0.2 * smoothstep(_crane(f)[0], _crane(f)[1], t))
        if not hasattr(sky, 'hero_star'):
            for cue_t, seed in ((b1, 41), (b2, 42)):
                star_burst(c, T, sx, sy, t - cue_t, scale=1.0, seed=seed)
        # end title
        te = f.cue('end_title')
        if t > te - 0.5:
            pt = _title_sys()
            _title.draw_title(c, pt, t, TITLE_C[0], TITLE_C[1], t_in=te, t_out=None,
                              sub_in=te + 2.0)

    # ---------------------------------------------------------------- sea + lighthouse
    x_b, y_b, s = _lighthouse_frame(f, hz)
    with cam.apply(c, 1.0):
        off = hz - HZ
        sea.ocean(c, T, horizon_y=HZ, lights=[(x_b, y_b - 445 * s - off, '#ffd36b', 0.9, y_b - off)])
    draw_lighthouse_group(c, T, x_b, y_b, s, hz, pose_fn=_deng(f, fl), lamp=1.0, beam=1.0, deng_x=-0.55,
                          deng_mode='on_rail', deng_scale=0.12)

    # ---------------------------------------------------------------- credits
    tc = f.cue('credits')
    if t > tc - 0.1:
        y0 = 700.0
        for i, (txt, size, colr, a0) in enumerate(CREDITS):
            ti = tc + 0.45 * i
            a = smoothstep(ti, ti + 1.2, t)
            if a <= 0:
                continue
            dy = (1 - ease_out(clamp((t - ti) / 1.6))) * 12
            fnt = font(size, FONT_SERIF)
            y = y0 + i * 52 + (8 if i == 2 else 0)
            sh = skia.Paint(AntiAlias=True, Color=col('#000010', 0.5 * a))
            sh.setMaskFilter(skia.MaskFilter.MakeBlur(skia.kNormal_BlurStyle, 4))
            draw_text(c, txt, W / 2, y + dy + 2, fnt, sh)
            draw_text(c, txt, W / 2, y + dy, fnt, skia.Paint(AntiAlias=True, Color=col(colr, a0 * a)))

    # ---------------------------------------------------------------- grade
    f.grade.update(
        bloom=1.15 + 0.5 * fl,
        vignette=0.5,
        black=smoothstep(f.cue('fade_out'), f.dur - 0.05, t),
    )
